apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app.kubernetes.io/instance: coder
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "vote"
    port: 8080
  selector:
    app: vote
